name = "pong-game"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"

# Custom domain routes
routes = [
  { pattern = "pong.emilycogsdill.com", custom_domain = true, zone_name = "emilycogsdill.com" }
]

[[env.production]]
name = "pong-game-prod"
routes = [
  { pattern = "pong.emilycogsdill.com", custom_domain = true, zone_name = "emilycogsdill.com" }
]

[[env.staging]]
name = "pong-game-staging"