name = "pong"
compatibility_date = "2025-01-01"

# Custom domain routes
routes = [
  { pattern = "pong.emilycogsdill.com", custom_domain = true, zone_name = "emilycogsdill.com" }
]

# Assets configuration
[assets]
directory = "./public"

